# Generated by Django 2.0.7 on 2019-07-17 21:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import simple_history.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('type', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DetailOperation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='HistoricalOperation',
            fields=[
                ('id', models.IntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('date_operation', models.DateTimeField(blank=True, editable=False)),
                ('idempotency_token', models.CharField(max_length=200)),
                ('token', models.CharField(blank=True, max_length=200, null=True)),
                ('status', models.CharField(default='created', max_length=200)),
                ('user_ip_address', models.CharField(max_length=200)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_date', models.DateTimeField()),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('type_operation', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='type.Type')),
                ('user', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-history_date', '-history_id'),
                'verbose_name': 'historical operation',
                'get_latest_by': 'history_date',
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='Operation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_operation', models.DateTimeField(auto_now=True)),
                ('idempotency_token', models.CharField(max_length=200)),
                ('token', models.CharField(blank=True, max_length=200, null=True)),
                ('status', models.CharField(default='created', max_length=200)),
                ('user_ip_address', models.CharField(max_length=200)),
                ('type_operation', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='fk_operation_type', to='type.Type')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='fk_operation_user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='detailoperation',
            name='operation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='fk_operation_detail', to='operation.Operation'),
        ),
        migrations.AddField(
            model_name='detailoperation',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='fk_operation_product', to='product.Product'),
        ),
    ]
