# Generated by Django 2.0.7 on 2019-07-17 21:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('operation', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historicaloperation',
            name='type_operation',
        ),
        migrations.RemoveField(
            model_name='operation',
            name='type_operation',
        ),
    ]
