# Generated by Django 2.0.7 on 2019-07-17 22:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operation', '0002_auto_20190717_1606'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicaloperation',
            name='idempotency_token',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='operation',
            name='date_operation',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='operation',
            name='idempotency_token',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
